services:
  web:
    build: ./ui
    ports:
      - "8000:8000"
    restart: always
    environment:
      - MONGO_URL=mongodb://admin:password@db:27017
      - PORT=8000

  db:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  mongo-express:
    image: mongo-express:1.0
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: db
    restart: always
volumes:
  db_data: {}
